import pyautogui
import time

pyautogui.FAILSAFE = True
pyautogui.PAUSE = 1
print("Opening Chrome in seconds..")
time.sleep(2)
pyautogui.hotkey("win", "r")
time.sleep(1)
pyautogui.write("chrome", interval=0.1)
pyautogui.press("enter")
time.sleep(2)
pyautogui.hotkey("ctrl", "t")
pyautogui.write(    "https://loremipsum.io/generator/",  interval=0.1)
pyautogui.press("enter")
time.sleep(5)
screenshot = pyautogui.screenshot()
screenshot.save("screenshot3.png")
print("Screenshot saved successfully")
pyautogui.hotkey("ctrl", "a")
time.sleep(2)
pyautogui.hotkey("ctrl", "c")
time.sleep(2)
pyautogui.hotkey("win", "r")
time.sleep(1)
pyautogui.write("winword", interval=0.1)
pyautogui.press("enter")
time.sleep(6)
pyautogui.press("enter")
time.sleep(2)
pyautogui.hotkey("ctrl", "v")
time.sleep(2)
pyautogui.hotkey("ctrl", "s")
time.sleep(2)
pyautogui.write("loremipsum generator",interval=0.1)
pyautogui.press("enter")
time.sleep(4)
screenshot = pyautogui.screenshot()
screenshot.save("screenshot4.png")
print("Final screenshot saved successfully")
pyautogui.hotkey("alt", "f4")
time.sleep(2)
pyautogui.hotkey("alt", "f4")
time.sleep(2)
print("Text saved successfully")
close_winword.close()
close_chrome.close()

